schema_version: 1

context:
  name: python-datauri
  version: 3.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/python_datauri-${{ version }}.tar.gz
  sha256: d77c37f1f734fc035de424e643464990b2b840e9b8c7c1817c11fca19b71eeb7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - cached-property
    - typing_extensions

tests:
  - python:
      imports:
        - datauri
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A li'l class for data URI manipulation in Python
  license: Unlicense
  license_file: LICENSE
  homepage: https://github.com/fcurella/python-datauri/

extra:
  recipe-maintainers:
    - shermansiu
